clear all; clc

addpath(genpath("/zhome/dd/4/109414/Validationstudy/accusleep_v2/AccuSleep/"))

imageLocations = {'/work3/laurose/accusleep/data/labAlessandro/',...
                  '/work3/laurose/accusleep/data/labAntoine/',...
                  '/work3/laurose/accusleep/data/labKornum/',...
                  '/work3/laurose/accusleep/data/labMaiken/',...
                  '/work3/laurose/accusleep/data/labSebastian/'};
fileLists      = ["fileList_test_Alessandro","fileList_test_Antoine","fileList_test_Kornum","fileList_test_Maiken","fileList_test_Sebastian"];

weights        = {[.0535 .5301 .4164],...
                   [0.0557,0.4815,0.4628],...
                   [0.0628,0.549,0.3882],...
                   [0.0729,0.2815,0.6456],...
                   [0.0676,0.4792,0.4532]};

for j = 1:length(fileLists)
    load(fileLists(j))
    SR            = 128; 
    epochLen      = 4; 
    epochs        = 9; 
    minBoutLen    = 5; 
    preprocess_images(fileList, SR, epochLen, epochs, imageLocations{j},weights{j})
end 
